# SOLEX LOGISTICS - GPT-Image-1 Generation Configuration
# GPT-Image-1 image generation settings for the corporate website

project_name: "solex-logistics"
output_dir: "./images"
filename_prefix: "solex"

# GPT-Image-1 specific parameters
default_model: "gpt-image-1"
default_size: "1024x1024"
default_quality: "medium"
default_n: 1

# Valid options:
# sizes: "1024x1024", "1024x1536", "1536x1024"
# qualities: "low", "medium", "high"
# n: 1-10 (number of images to generate)

# Pricing reference:
# Low: $0.011 (1024x1024), $0.016 (larger)
# Medium: $0.042 (1024x1024), $0.063 (larger)  
# High: $0.167 (1024x1024), $0.25 (larger)